services:
  mysql:
    build: ./mysql/ 
    image: lbghackathoncontainerregistry.azurecr.io/hackathon22-pythonapp
    restart: always
    environment:
      MYSQL_DATABASE: 'db'   
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'

  pythonapp:
    build: ./python/
    image: lbghackathoncontainerregistry.azurecr.io/hackathon22-mysql
    command: sh -c "sleep 60s ; python3 ./hello_world.py"
    depends_on:
      - mysql

 
      