# Generated by Django 3.1.1 on 2022-11-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reboot', '0002_auto_20221117_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_input', models.FloatField(default=0)),
                ('inflation_input', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Input',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductCategory', models.CharField(max_length=100)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductPrice', models.FloatField()),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
