# Generated by Django 4.1.3 on 2022-11-18 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='ProductName',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productPrice',
            new_name='ProductPrice',
        ),
        migrations.AddField(
            model_name='product',
            name='ProductID',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
