# Generated by Django 4.1.3 on 2022-11-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_productname_product_productname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductID',
        ),
    ]
