# Generated by Django 4.1.3 on 2022-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_product_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductID',
            field=models.IntegerField(default=0),
        ),
    ]
